### ISSUE TITLE
Add option to limit size

### ISSUE THREAD

**Issue by gabdsg** [lijungegea/flutter_simple_image_crop#1]
It would be nice to have an option to limit the size of the resulting image.
Something like 
`crop.cropCompleted(image, pictureQuality: 900, maxWidth: 500)`
or
`ImgCrop(
   key: cropKey,
   maxWidth: 500,
   image: FileImage(image))`

**Comment by lijungegea** [comment]
you may be use chipRadius limit croped size:
`chipRadius: 150,  // crop area radius`
`chipRadius` param determines the size of the cropped image

**Comment by lijungegea** [comment]
> you may be use chipRadius limit croped size:
> `chipRadius: 150, // crop area radius`
> `chipRadius` param determines the size of the cropped image

**Comment by lijungegea** [comment]
> It would be nice to have an option to limit the size of the resulting image.
> Something like
> `crop.cropCompleted(image, pictureQuality: 900, maxWidth: 500)`
> or
> `ImgCrop( key: cropKey, maxWidth: 500, image: FileImage(image))`

Give me a star to support !

**Comment by gabdsg** [comment]
> you may be use chipRadius limit croped size:
> `chipRadius: 150, // crop area radius`
> `chipRadius` param determines the size of the cropped image

I have chipRadius = 150 but the image size is not 150. (iOS)

**Comment by lijungegea** [comment]
> > you may be use chipRadius limit croped size:
> > `chipRadius: 150, // crop area radius`
> > `chipRadius` param determines the size of the cropped image
> 
> I have chipRadius = 150 but the image size is not 150. (iOS)

sorry ! `cropCompleted` params `pictureQuality` can control image size , 
I didn't understand what you meant before .
