### ISSUE TITLE
可以裁剪矩形么？

### ISSUE THREAD

**Issue by AllisonWangJiaoJiao** [lijungegea/flutter_simple_image_crop#18]
可以裁剪4：3或者16：9的矩形嘛？
    // NOTE: 相对于整体图片已显示的view大小， viewWidth - 1.0 为未显示区域， / 2 算出 left的比例模型
        _view = Rect.fromLTWH(
          (viewWidth - 1.0) / 2,
          (viewHeight - 1.0) / 2,
          viewWidth,
          viewHeight,
        );

**Comment by lijungegea** [comment]
暂时不支持

AllisonWangJiaoJiao <notifications@github.com> 于2020年9月22日周二 下午2:37写道：

**Comment by lijungegea** [comment]
后面发布正式版1.0.0会支持，感谢关注
