### ISSUE TITLE
Package install issue!

### ISSUE THREAD

**Issue by zl910627** [lijungegea/flutter_simple_image_crop#19]
Invalid plugin specification simple_image_crop.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml`

**Comment by lijungegea** [comment]
update flutter version

zl910627 <notifications@github.com> 于2020年9月27日周日 下午10:39写道：

**Comment by zl910627** [comment]
![Uploading image.png…]()

**Comment by zl910627** [comment]
![image](https://user-images.githubusercontent.com/53897531/94589395-cad29080-02b7-11eb-92e8-da1ba96a4a1d.png)

**Comment by zl910627** [comment]
Invalid plugin specification simple_image_crop.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here:

still same issue!

**Comment by gabdsg** [comment]
same issue here

**Comment by justitman123** [comment]
still the same issue!

**Comment by ScottOber** [comment]
Please show all steps to resolve this issue when including "simple_image_crop: ^1.0.0" in pubspec.yaml.

If pull request #21 fixes the issue, how do I apply it and where?

Wouldn't it be easier to release "simple_image_crop: ^1.0.1" that just works?
