### ISSUE TITLE
示例工程报错

### ISSUE THREAD

**Issue by BedRockGx** [lijungegea/flutter_simple_image_crop#2]
具体报错点在lib>src>simpleCrop.dart中第54行，
报错信息:
Compiler message:
../lib/src/simpleCrop.dart:54:20: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/E:/flutter_1.9+/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
    return context.findAncestorStateOfType();

**Comment by lijungegea** [comment]
> 具体报错点在lib>src>simpleCrop.dart中第54行，
> 报错信息:
> Compiler message:
> ../lib/src/simpleCrop.dart:54:20: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
> 
> * 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/E:/flutter_1.9+/flutter/packages/flutter/lib/src/widgets/framework.dart').
>   Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
>   return context.findAncestorStateOfType();

请升级最新版flutter， 再次尝试，'findAncestorStateOfType' 是新版本API

**Comment by Airsola** [comment]
@Deprecated('Use findAncestorStateOfType instead. ' 'This feature was deprecated after v1.12.1.'), override
