### ISSUE TITLE
Invalid plugin specification simple_image_crop

### ISSUE THREAD

**Issue by vemarav** [lijungegea/flutter_simple_image_crop#26]
Invalid plugin specification simple_image_crop.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

**Comment by abeticlairon** [comment]
How did you fix it?

**Comment by vemarav** [comment]
https://github.com/brewhackers-technologies/flutter_simple_image_crop/blob/master/pubspec.yaml

**Comment by yasinarik** [comment]
> @abeticlairon update pubspec.yaml with following pubspec
> 
> https://github.com/brewhackers-technologies/flutter_simple_image_crop/blob/master/pubspec.yaml

How to do that? I don't really get it?  Could you please show how more openly? Thanks a lot! @vemarav
