### ISSUE TITLE
Circle crop is rect

### ISSUE THREAD

**Issue by mudlee** [lijungegea/flutter_simple_image_crop#8]
I might misunderstood the project, but in my mind I can crop out a rect **or** a circular part of an image.
But even the image shows that even if I crop with circle, that it will be a rect in the end. Is there any possible chance to crop out really a circle?

![Image](https://github.com/lijungegea/flutter_simple_image_crop/raw/master/assets/circle.gif)

**Comment by QuentinSc** [comment]
I'm agree it could be great to have the choice

**Comment by furaiev** [comment]
Come on guys, where do you see a circle image file?
A File is always square, there can be transparency but not the real shape.

**Comment by lijungegea** [comment]
where do you see a circle image file
